---
driver:
  name: azurerm

driver_config:
  subscription_id: 829eeca2-0445-402d-bf81-4d00f1093c64
  location: West US
  machine_size: Standard_A1

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows2012-r2
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
      vm_name: azurex1
    transport:
      name: winrm
      username: azure
      password: P2ssw0rd

suites:
  - name: default
    run_list:
      - recipe[azurex1::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
